S = input()

print(S.find('a'),
      S.find('b'),
      S.find('c'),
      S.find('d'),
      S.find('e'),
      S.find('f'),
      S.find('g'),
      S.find('h'),
      S.find('i'),
      S.find('j'),
      S.find('k'),
      S.find('l'),
      S.find('m'),
      S.find('n'),
      S.find('o'),
      S.find('p'),
      S.find('q'),
      S.find('r'),
      S.find('s'),
      S.find('t'),
      S.find('u'),
      S.find('v'),
      S.find('w'),
      S.find('x'),
      S.find('y'),
      S.find('z'))